file:
   filepath: f:/test/m1
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可
spring:
  datasource:
    url: jdbc:mysql://123.56.193.124:3306/scity?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Aduan1234
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
         max-file-size: 512000000000     # 文件上传大小限制为500kb
         max-request-size: 512000000000  # 请求大小限制为500kbb
  http:
      multipart:
         maxFileSize: 100Mb
         maxRequestSize: 1000Mb         